### ISSUE TITLE
Github doesn't parse README.rst properly

### ISSUE THREAD

**Issue by coroa** [openmod-initiative/toolchest#4]
https://github.com/openmod-initiative/toolchest

looks broken.

**Comment by ojdo** [comment]
It _should_ work though, if the rst is "fine". [This README.rst](https://github.com/jkbrzt/httpie/blob/master/README.rst) renders fine, for example. This historic [rst Issue on GitHub/markup](https://github.com/github/markup/issues/265) hints that the converter might run into an error on our document (legitimately or not) and thus returns the source as a fallback.

That said, I'm very fine with markdown.

**Comment by gidden** [comment]
Yes, it may also be true that I mixed a bit of rst and md. I don't
particularly care which one we go with.
